### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by FreakyFP** [codetheweb/aoede#13]
Hey first of all I want to say that's a nice bot,

but I never used Docker and because of this I don't know how to install the bot, I am using Mac OS

Thank you

**Comment by codetheweb** [comment]
If you want to use Docker (which I would recommend) you could try going through a tutorial [like this one](https://www.educative.io/blog/docker-compose-tutorial) to set up Docker Compose.

Otherwise there is a pre-built binary available for macOS (see the [README](https://github.com/codetheweb/aoede#-usage)).
